### ISSUE TITLE
Support selecting signing algorithim

### ISSUE THREAD

**Issue by dekobon** [joyent/java-http-signature#10]
Currently in the node.js Manta SDK, the signing algorithm of the ssh key fingerprint is specified before the fingerprint as such:
```
SHA256:/jZc62ogo+V3sMvtaejk1z593wIrfd8ruslxzoc4ebc
MD5:30:f1:55:f3:8b:fa:b8:3d:e9:c7:7a:23:43:cf:ae:46
```

However, in the previous versions of the node.js Manta SDK, the ssh key fingerprint was specfied only as a MD5 checksum in the following format:
```
30:f1:55:f3:8b:fa:b8:3d:e9:c7:7a:23:43:cf:ae:46
```

This issue involves changing the HTTP signatures library to do the following:
1. Support checksums that are not just MD5.
2. To detect the checksum used by parsing the checksum name from the fingerprint string.
3. To maintain support for existing checksums that do not contain a checksum name prefix.

**Comment by cburroughs** [comment]
How are #6 and #10 different?

**Comment by dekobon** [comment]
They are the same.

**Comment by cburroughs** [comment]
So how node handled this (and I think this makes sense as an approach to mirror) is that the fingerprint given by the user is only used to automatically find the key in `~/.ssh`.  The fingerprint passed to to the server would then be calculated on the fly (the server still only supports unadorned md5).

However, to do that we need to actually calculate the fingerprint, which is based on openssh's own special format and not a "standard".  As far as I can tell there is nothing in the java standard library *or* BouncyCastle that does this.  The only think I have found that handles more than RSA keys is https://github.com/hierynomus/sshj (RSA is simple enough for a stackoverflow question,  ECDSA not so much.)

Options:
 (A) Pull in sshj.  I think this is too big, adds more transitive deps, and could leave us fighting over BC versions.
 (B) Pull out and modify several ALv2 classes from sshj to do the minimal amount to calculate fingerprints.  This looks like more than a single class.
 (C) Someone else finds another library.

I'm leaning towards (B) as the least bad option, unless something pops up for (C).

**Comment by rmustacc** [comment]
On 3/21/17 8:10 , cburroughs wrote:
> So how node handled this (and I think this makes sense as an approach to mirror) is that the fingerprint given by the user is only used to automatically find the key in `~/.ssh`.  The fingerprint passed to to the server would then be calculated on the fly (the server still only supports unadorned md5).
> 
> However, to do that we need to actually calculate the fingerprint, which is based on openssh's own special format and not a "standard".  As far as I can tell there is nothing in the java standard library *or* BouncyCastle that does this.  The only think I have found that handles more than RSA keys is https://github.com/hierynomus/sshj (RSA is simple enough for a stackoverflow question,  ECDSA not so much.)
> 
> Options:
>  (A) Pull in sshj.  I think this is too big, adds more transitive deps, and could leave us fighting over BC versions.
>  (B) Pull out and modify several ALv2 classes from sshj to do the minimal amount to calculate fingerprints.  This looks like more than a single class.
>  (C) Someone else finds another library.
> 
> I'm leaning towards (B) as the least bad option, unless something pops up for (C).
> 

Another thing to keep in mind is that the encrypted format of the
OpenSSH key format was recently changed to something more
OpenBSD/OpenSSH specific and isn't a more general standard. Dunno if
that really changes anything, but just wanted to make sure you were aware.

Robert

**Comment by dekobon** [comment]
(B) sounds the best. However, this issue isn't blocking anyone, so I would view it as low-priority.

**Comment by cburroughs** [comment]
I tried to pull in sshj, but there turned out to be too many interdependent classes to do cleanly.  After returning to node-sshpk again and talking to Alex, I think I've implemented fingerprint generation for DSA/RSA/ECDSA and am moving forward based on that.
