### ISSUE TITLE
write changelog for 4.0.0 release

### ISSUE THREAD

**Issue by cburroughs** [joyent/java-http-signature#16]
(This is easier for me to do conflict free after everything lands.)

**Comment by dekobon** [comment]
Are we breaking compatibility for any of these changes? If we are just adding functionality, incrementing a minor version number of 3.x may be sufficient.

**Comment by cburroughs** [comment]
Formally yes (for example a constant `public static final String SIGNING_JVM_ALGORITHM` does not make any sense in a world with multiple signing algorithms).  In practice, zero changes to java-manta were needed to run the integration tests with the (unchanged) default signing algorithm..
