### ISSUE TITLE
Support ECDSA signing

### ISSUE THREAD

**Issue by dekobon** [joyent/java-http-signature#9]

**Comment by cburroughs** [comment]
Still more testing and such to do.  But the initial benchmarks (on a reasonable container) look promising:

```
Benchmark                                  (hash)  (providerCode)   Mode  Cnt     Score   Error  Units
BenchmarkDSASigner.signHeaderThroughput    SHA256          stdlib  thrpt   75  2078.503 ± 2.914  ops/s
BenchmarkECDSASigner.signHeaderThroughput  SHA256          stdlib  thrpt   75  2934.387 ± 6.949  ops/s
BenchmarkRSASigner.signHeaderThroughput    SHA256          stdlib  thrpt   75   166.128 ± 2.133  ops/s
BenchmarkRSASigner.signHeaderThroughput    SHA256   native.jnagmp  thrpt   75   725.252 ± 2.747  ops/s
```

**Comment by dekobon** [comment]
:+1:

**Comment by arekinath** [comment]
2923 ops/sec is still really slow for ECDSA... I guess that's using the pure Java bignum bits in Bouncy Castle?

**Comment by dekobon** [comment]
I would like to see a branch with this implemented. Then we can try to run the same benchmark with libnss installed via PKCS11. It may yield different results.

**Comment by cburroughs** [comment]
I think I have a way to get [NSS](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS) working with this that isn't too error prone.  That would (assuming a user is willing to jump through all of the hooks to use NSS by way of PKCS11) provide the following improvements:

```
"BC" aka "default"
Benchmark                                  (hash)  (providerCode)   Mode  Cnt     Score   Error  Units
BenchmarkECDSASigner.signHeaderThroughput  SHA256          stdlib  thrpt   75  2938.322 ± 6.516  ops/s

nss via magical config files
Benchmark                                  (hash)  (providerCode)   Mode  Cnt     Score   Error  Units
BenchmarkECDSASigner.signHeaderThroughput  SHA256          stdlib  thrpt   75  4465.342 ± 8.012  ops/s
```

**Comment by dekobon** [comment]
Could you do another benchmark with the default JVM implementation (Sun)? I think all you would need to do is disable NSS from the providers list. I'm curious about how far off BC is from the default implementation. In the case of cryptographic checksums, it was quite a ways off.

**Comment by cburroughs** [comment]
```
#Signature-->Provider: SunEC
Benchmark                                  (hash)  (providerCode)   Mode  Cnt     Score   Error  Units
BenchmarkECDSASigner.signHeaderThroughput  SHA256          stdlib  thrpt   75  1162.469 ± 3.902  ops/s
```

**Comment by dekobon** [comment]
Wow, so the answer is we want libnss or BC.
